services:
  locamais:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
      - 5173:5173
    volumes:
      - ./:/var/www/
    networks:
      - locamais
    tty: true
    container_name: locamais

  mysql_locamais:
    image: mariadb:10.3
    entrypoint: docker-entrypoint.sh --sql-mode='STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ports:
      - 3306:3306
    networks:
      - locamais
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=locamais
    container_name: mysql_locamais
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin_locamais:
    image: beeyev/phpmyadmin-lightweight
    ports:
      - 8181:80
    networks:
      - locamais
    environment:
      PMA_HOST: mysql_locamais
      PMA_THEME: BooDark
      UPLOAD_LIMIT: 2000M
    container_name: phpmyadmin_locamais

networks:
  locamais:
    external: true

volumes:
  mysql_data:
